# Generated by Django 5.0.7 on 2024-09-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0003_granitefallsforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granitefallsforecast',
            name='river_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='granitefallsgauge',
            name='river_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jordanroadgauge',
            name='river_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='verlotgauge',
            name='river_id',
            field=models.IntegerField(null=True),
        ),
    ]
