# Generated by Django 5.0.7 on 2024-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0005_delete_verlotgauge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granitefallsforecast',
            name='river_id',
        ),
        migrations.RemoveField(
            model_name='granitefallsgauge',
            name='river_id',
        ),
        migrations.AlterUniqueTogether(
            name='jordanroadgauge',
            unique_together={('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='jordanroadgauge',
            name='river_id',
        ),
    ]
