# Generated by Django 5.0.7 on 2024-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0009_alpinemeadowsgauge_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedgauges',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
