# Generated by Django 5.0.7 on 2024-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0010_alter_combinedgauges_date_alter_combinedgauges_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedpredictions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinedpredictions',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
