# Generated by Django 5.0.7 on 2024-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0012_alter_granitefallsprediction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granitefallsforecast',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='granitefallsforecast',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='granitefallsgauge',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='granitefallsgauge',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jordanroadgauge',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jordanroadgauge',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
