# Generated by Django 5.0.7 on 2024-09-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0015_alter_granitefallspredictionarchive_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='granitefallsforecast',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='granitefallsprediction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='granitefallsforecast',
            name='date',
        ),
        migrations.RemoveField(
            model_name='granitefallsforecast',
            name='time',
        ),
        migrations.RemoveField(
            model_name='granitefallsprediction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='granitefallsprediction',
            name='time',
        ),
    ]
