# Generated by Django 5.0.7 on 2024-09-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0016_alter_granitefallsforecast_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='combinedpredictions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='combinedpredictions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='combinedpredictions',
            name='time',
        ),
    ]
