# Generated by Django 5.0.7 on 2024-09-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0019_alter_granitefallsgauge_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='combinedgauges',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='combinedgauges',
            name='date',
        ),
        migrations.RemoveField(
            model_name='combinedgauges',
            name='time',
        ),
    ]
