# Generated by Django 5.0.7 on 2024-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0020_alter_combinedgauges_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpinemeadowsgauge',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='combinedpredictions',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='granitefallsforecast',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='granitefallsgauge',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='granitefallsprediction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jordanroadgauge',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
