# Generated by Django 5.0.7 on 2024-09-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0023_rename_accuracyperiod_accuracymetrics_accuracy_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuracymetrics',
            old_name='mae_score',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='accuracymetrics',
            old_name='mse_score',
            new_name='mse',
        ),
        migrations.RenameField(
            model_name='accuracymetrics',
            old_name='r2_score',
            new_name='r2',
        ),
    ]
