# Generated by Django 5.0.7 on 2024-09-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0025_rename_gauge_a_name_combinedgauges_gauge_1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combinedgauges',
            old_name='gauge_1_name',
            new_name='gauge_A_name',
        ),
        migrations.RenameField(
            model_name='combinedgauges',
            old_name='gauge_1_stage',
            new_name='gauge_A_stage',
        ),
        migrations.RenameField(
            model_name='combinedgauges',
            old_name='gauge_2_name',
            new_name='gauge_B_name',
        ),
        migrations.RenameField(
            model_name='combinedgauges',
            old_name='gauge_2_stage',
            new_name='gauge_B_stage',
        ),
    ]
