# Generated by Django 5.0.7 on 2024-09-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0029_granitefallsforecastlinear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraniteFallsForecastLinear',
            new_name='GraniteFallsPredictionLinear',
        ),
    ]
