# Generated by Django 5.0.7 on 2024-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0031_granitefallsforecastlinear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteFallsPredictionLinearArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_datetime', models.DateTimeField()),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('forecast_datetime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('prediction_datetime', 'forecast_datetime')},
            },
        ),
    ]
