# Generated by Django 5.0.7 on 2024-09-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0033_accuracymetricslinear_averagepredictionlinear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedGauges',
        ),
    ]
