# Generated by Django 5.0.7 on 2024-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0034_delete_combinedgauges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedGauges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('gauge_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_1_stage', models.FloatField(blank=True, null=True)),
                ('gauge_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_2_stage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
