services:
  db:
    image: rhealy5/robeforecast-mysql
    container_name: robeforecast-mysql
    environment:
      MYSQL_HOST: robeforecast-mysql
      MYSQL_DATABASE: robe_forecast_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: weeTh0oh
      MYSQL_ROOT_PASSWORD: weeTh0oh
    volumes:
      - db-data:/var/lib/mysql
      - ./legacy_data.sql:/docker-entrypoint-initdb.d/legacy_data.sql
    ports:
      - "3307:3306"
    networks:
      - app-network

  django:
    image: rhealy5/robeforecast-django
    container_name: robeforecast-django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: robeforecast-mysql
      MYSQL_DATABASE: robe_forecast_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: weeTh0oh
      MYSQL_ROOT_PASSWORD: weeTh0oh
      DEBUG: 0
      SECRET_KEY: django-insecure-@0&e8tn()t3%e#c2cv4=h7wh*y+z58_p#56za-b+#v&j(#piok
    volumes:
      - .:/app
    networks:
      - app-network

  redis:
    image: rhealy5/robeforecast-redis
    container_name: robeforecast-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  angular:
    image: rhealy5/robeforecast-angular
    container_name: robeforecast-angular
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
