# Generated by Django 5.0.7 on 2024-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_period', models.IntegerField()),
                ('mse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyMetricsLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_period', models.IntegerField()),
                ('mse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlpineMeadowsGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('snow_water_equivalent', models.FloatField()),
                ('snow_depth', models.FloatField()),
                ('precipitation_accumulation', models.FloatField()),
                ('air_temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlpineMeadowsWeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('temp', models.FloatField()),
                ('rain_3h', models.FloatField()),
                ('snow_3h', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AveragePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(unique=True)),
                ('average_predicted_stage', models.FloatField()),
                ('observed_stage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AveragePredictionLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(unique=True)),
                ('average_predicted_stage', models.FloatField()),
                ('observed_stage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedGauges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('gauge_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_1_stage', models.FloatField(blank=True, null=True)),
                ('gauge_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_2_stage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('sp_temp', models.FloatField(blank=True, null=True)),
                ('sp_rain_3h', models.FloatField(blank=True, null=True)),
                ('sp_snow_3h', models.FloatField(blank=True, null=True)),
                ('ap_temp', models.FloatField(blank=True, null=True)),
                ('ap_rain_3h', models.FloatField(blank=True, null=True)),
                ('ap_snow_3h', models.FloatField(blank=True, null=True)),
                ('gauge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_stage', models.FloatField(blank=True, null=True)),
                ('am_snow_water_equivalent', models.FloatField(blank=True, null=True)),
                ('am_snow_depth', models.FloatField(blank=True, null=True)),
                ('am_precipitation_accumulation', models.FloatField(blank=True, null=True)),
                ('am_air_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraniteFallsForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('prediction_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraniteFallsForecastLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('prediction_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraniteFallsGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('stage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraniteFallsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('sp_temp', models.FloatField(blank=True, null=True)),
                ('sp_rain_3h', models.FloatField(blank=True, null=True)),
                ('sp_snow_3h', models.FloatField(blank=True, null=True)),
                ('ap_temp', models.FloatField(blank=True, null=True)),
                ('ap_rain_3h', models.FloatField(blank=True, null=True)),
                ('ap_snow_3h', models.FloatField(blank=True, null=True)),
                ('am_snow_water_equivalent', models.FloatField(blank=True, null=True)),
                ('am_snow_depth', models.FloatField(blank=True, null=True)),
                ('am_precipitation_accumulation', models.FloatField(blank=True, null=True)),
                ('am_air_temperature', models.FloatField(blank=True, null=True)),
                ('gauge_A_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge_A_stage', models.FloatField(blank=True, null=True)),
                ('gauge_B_name', models.CharField(max_length=100)),
                ('gauge_B_stage', models.FloatField()),
                ('prediction_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraniteFallsPredictionLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('prediction_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JordanRoadGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('stage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SilvertonWeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('temp', models.FloatField()),
                ('rain_3h', models.FloatField()),
                ('snow_3h', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GraniteFallsPredictionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_datetime', models.DateTimeField()),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('forecast_datetime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('prediction_datetime', 'forecast_datetime')},
            },
        ),
        migrations.CreateModel(
            name='GraniteFallsPredictionLinearArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_datetime', models.DateTimeField()),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('forecast_datetime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('prediction_datetime', 'forecast_datetime')},
            },
        ),
    ]
