# Generated by Django 5.0.7 on 2024-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riverID', models.IntegerField()),
                ('riverName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('stage', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
