# Generated by Django 5.0.7 on 2024-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteFallsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sp_temp', models.FloatField(blank=True, null=True)),
                ('sp_rain_3h', models.FloatField(blank=True, null=True)),
                ('sp_snow_3h', models.FloatField(blank=True, null=True)),
                ('ap_temp', models.FloatField(blank=True, null=True)),
                ('ap_rain_3h', models.FloatField(blank=True, null=True)),
                ('ap_snow_3h', models.FloatField(blank=True, null=True)),
                ('am_snow_water_equivalent', models.FloatField(blank=True, null=True)),
                ('am_snow_depth', models.FloatField(blank=True, null=True)),
                ('am_precipitation_accumulation', models.FloatField(blank=True, null=True)),
                ('am_air_temperature', models.FloatField(blank=True, null=True)),
                ('gauge2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gauge2_stage', models.FloatField(blank=True, null=True)),
                ('gauge1_name', models.CharField(max_length=100)),
                ('gauge1_stage', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
