# Generated by Django 5.0.7 on 2024-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedGauges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('gauge_1_name', models.CharField(max_length=100)),
                ('gauge_1_stage', models.FloatField()),
                ('gauge_2_name', models.CharField(max_length=100)),
                ('gauge_2_stage', models.FloatField()),
                ('gauge_3_name', models.CharField(max_length=100)),
                ('gauge_3_stage', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
