# Generated by Django 5.0.7 on 2024-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riverdata',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='riverdata',
            name='stage',
            field=models.FloatField(),
        ),
    ]
