# Generated by Django 5.0.7 on 2024-08-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0002_combinedgauges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedgauges',
            name='gauge_3_stage',
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='gauge_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='gauge_1_stage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='gauge_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='gauge_2_stage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combinedgauges',
            name='gauge_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
