# Generated by Django 5.0.7 on 2024-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0002_granitefallsprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteFallsForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river_id', models.IntegerField()),
                ('gauge_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('stage', models.FloatField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('river_id', 'date', 'time')},
            },
        ),
    ]
