# Generated by Django 5.0.7 on 2024-08-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0003_remove_combinedgauges_gauge_3_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedgauges',
            name='gauge_3_stage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
