# Generated by Django 5.0.7 on 2024-09-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0004_alter_granitefallsforecast_river_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerlotGauge',
        ),
    ]
