# Generated by Django 5.0.7 on 2024-08-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0004_combinedgauges_gauge_3_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilvertonWeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temp', models.FloatField()),
                ('rain_1h', models.FloatField()),
                ('rain_3h', models.FloatField()),
                ('snow_1h', models.FloatField()),
                ('snow_3h', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
