# Generated by Django 5.0.7 on 2024-08-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0005_silvertonweatherprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpineMeadowsGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('snow_water_equivalent', models.FloatField()),
                ('snow_depth', models.FloatField()),
                ('precipitation_accumulation', models.FloatField()),
                ('air_temperature', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
