# Generated by Django 5.0.7 on 2024-08-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0006_alpinemeadowsgauge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silvertonweatherprediction',
            name='rain_1h',
        ),
        migrations.RemoveField(
            model_name='silvertonweatherprediction',
            name='snow_1h',
        ),
        migrations.RemoveField(
            model_name='silvertonweatherprediction',
            name='snow_3h',
        ),
    ]
