# Generated by Django 5.0.7 on 2024-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0011_alter_combinedpredictions_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granitefallsprediction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='granitefallsprediction',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
