# Generated by Django 5.0.7 on 2024-09-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0013_alter_granitefallsforecast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteFallsPredictionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_datetime', models.DateTimeField()),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('forecast_datetime', models.DateTimeField()),
            ],
        ),
    ]
