# Generated by Django 5.0.7 on 2024-09-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0014_granitefallspredictionarchive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='granitefallspredictionarchive',
            unique_together={('prediction_datetime', 'forecast_datetime')},
        ),
    ]
