# Generated by Django 5.0.7 on 2024-09-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0018_alter_alpinemeadowsgauge_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='granitefallsgauge',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='jordanroadgauge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='granitefallsgauge',
            name='date',
        ),
        migrations.RemoveField(
            model_name='granitefallsgauge',
            name='time',
        ),
        migrations.RemoveField(
            model_name='jordanroadgauge',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jordanroadgauge',
            name='time',
        ),
    ]
