# Generated by Django 5.0.7 on 2024-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0021_alter_alpinemeadowsgauge_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracyPeriod', models.IntegerField()),
                ('mse_score', models.FloatField()),
                ('mae_score', models.FloatField()),
                ('r2_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AveragePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(unique=True)),
                ('average_predicted_stage', models.FloatField()),
            ],
        ),
    ]
