# Generated by Django 5.0.7 on 2024-09-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0022_accuracymetrics_averageprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accuracymetrics',
            old_name='accuracyPeriod',
            new_name='accuracy_period',
        ),
        migrations.AddField(
            model_name='averageprediction',
            name='observed_stage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
