# Generated by Django 5.0.7 on 2024-09-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0024_rename_mae_score_accuracymetrics_mae_and_more.py'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combinegauges',
            old_name='gauge_1_name',
            new_name='gauge_B_name',
        ),
        migrations.RenameField(
            model_name='combinegauges',
            old_name='gauge_1_stage',
            new_name='gauge_B_stage',
        ),
        migrations.RenameField(
            model_name='combinegauges',
            old_name='gauge_2_name',
            new_name='gauge_A_name',
        ),
        migrations.RenameField(
            model_name='combinegauges',
            old_name='gauge_2_stage',
            new_name='gauge_A_stage',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge1_name',
            new_name='gauge_B_name',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge1_stage',
            new_name='gauge_B_stage',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge2_name',
            new_name='gauge_A_name',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge2_stage',
            new_name='gauge_A_stage',
        ),
    ]
