# Generated by Django 5.0.7 on 2024-09-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0027_rename_gauge_a_name_granitefallsprediction_gauge1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge1_name',
            new_name='gauge_A_name',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge1_stage',
            new_name='gauge_A_stage',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge2_name',
            new_name='gauge_B_name',
        ),
        migrations.RenameField(
            model_name='granitefallsprediction',
            old_name='gauge2_stage',
            new_name='gauge_B_stage',
        ),
    ]
