# Generated by Django 5.0.7 on 2024-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0028_rename_gauge1_name_granitefallsprediction_gauge_a_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteFallsForecastLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, unique=True)),
                ('gauge_name', models.CharField(max_length=100)),
                ('stage', models.FloatField()),
                ('prediction_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
