# Generated by Django 5.0.7 on 2024-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdata', '0032_granitefallspredictionlineararchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyMetricsLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_period', models.IntegerField()),
                ('mse', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AveragePredictionLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(unique=True)),
                ('average_predicted_stage', models.FloatField()),
                ('observed_stage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
